package com.proofpoint.discovery.monitor;

public enum DiscoveryEventType
{
    SERVICEQUERY,
    STATICANNOUNCEMENT,
    STATICANNOUNCEMENTLIST,
    STATICANNOUNCEMENTDELETE,
    DYNAMICANNOUNCEMENT,
    DYNAMICANNOUNCEMENTDELETE,
    STOREGET,
    STOREPUT,
    REPLICATIONPULL,
    REPLICATIONPUSH
}
